map_server/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from rest_framework.urlpatterns import format_suffix_patterns
from map_server import views

# Gross hack to serve under directory, not subdomain
prefix = settings.URL_PREFIX


urlpatterns = patterns('',
    url(r'^' + prefix + '$', views.UserSubmissionList.as_view(), name='moderation-home'),
    url(r'^' + prefix + '(?P<map_id>[0-9]+)/$', views.UserSubmissionList.as_view(), name='moderation-map'),
    url(r'^' + prefix + '(?P<map_id>[0-9]+)/approved_submissions.json$', views.UserSubmissionListPublic.as_view(), name='approved_submissions_feed'),
    # url(r'^' + prefix + 'plain/$', views.UserSubmissionListPublic.as_view(), name='usersubmission_feed'),

    url(r'^' + prefix + 'plain/post/$', views.UserSubmissionListPost.as_view(), name='user_submission_post'),
    url(r'^' + prefix + 'submission/(?P<pk>[0-9]+)/$', views.UserSubmissionDetail.as_view(), name='submission-detail'),

    url(r'^' + prefix + 'login/$', 'django.contrib.auth.views.login'),
    url(r'^' + prefix + 'logout/$', 'django.contrib.auth.views.logout', {'next_page': '/maps/'}),

    url(r'^' + prefix + 'mapmaker/maps/?$', views.MapList.as_view(), name='mapmaker-map-list'),
    url(r'^' + prefix + 'mapmaker/map/(?P<pk>[0-9]+)/?$', views.MapDetail.as_view(), name='mapmaker-map-detail'),
    url(r'^' + prefix + 'mapmaker/layers/?$', views.LayerList.as_view(), name='mapmaker-layer-list'),
    url(r'^' + prefix + 'mapmaker/layer/(?P<pk>[0-9]+)/?$', views.LayerDetail.as_view(), name='mapmaker-layer-detail'),
    url(r'^' + prefix + 'mapmaker/datasets/?$', views.LayerDatasetList.as_view(), name='mapmaker-dataset-list'),
    url(r'^' + prefix + 'mapmaker/dataset/(?P<pk>[0-9]+)/?$', views.LayerDatasetDetail.as_view(), name='mapmaker-dataset-detail'),
    url(r'^' + prefix + 'mapmaker/markericons/?$', views.MarkerIconList.as_view(), name='mapmaker-markericon-list'),
    url(r'^' + prefix + 'mapmaker/markericon/(?P<pk>[0-9]+)/?$', views.MarkerIconDetail.as_view(), name='mapmaker-markericon-detail'),

    url(r'^' + prefix + 'mapmaker/map/(?P<pk>[0-9]+)/preview/?$', views.MapPreview.as_view(), name='map-preview'),
    url(r'^' + prefix + 'mapmaker/map/(?P<pk>[0-9]+)/publish/?$', views.MapPublish.as_view(), name='map-publish'),
)


urlpatterns = format_suffix_patterns(urlpatterns)
urlpatterns += patterns('',
    url(r'^' + prefix + 'auth/', include('rest_framework.urls', namespace='rest_framework')),
)


urlpatterns += patterns('',
    url(r'^' + prefix + 'user_submission_email_addresses.csv$', views.user_submission_email_addresses, name='email-addresses-csv'),
    url(r'^' + prefix + 'utils/convert-en-to-latlng/$', login_required(views.ConvertEnToLatLng.as_view()), name='convert-en-to-latlng'),
    url(r'^' + prefix + 'utils/bulk-geocode/$', login_required(views.BulkGeocode.as_view()), name='bulk-geocode'),
)

urlpatterns += patterns('',
    url(r'^' + prefix + 'mapmaker/$', login_required(TemplateView.as_view(template_name="map_maker/index.html")), name='mapmaker-home'),
    url(r'^' + prefix + 'mapmaker/controller.js$', TemplateView.as_view(template_name="map_maker/controller.js"), name='mapmaker-controller'),
    url(r'^' + prefix + 'mapmaker/partial/map.html$', TemplateView.as_view(template_name="map_maker/partials/map.html"), name='mapmaker-partial-map'),
    url(r'^' + prefix + 'mapmaker/partial/header.html$', TemplateView.as_view(template_name="map_maker/partials/header.html"), name='mapmaker-partial-header'),
    url(r'^' + prefix + 'mapmaker/partial/detail.html$', TemplateView.as_view(template_name="map_maker/partials/detail.html"), name='mapmaker-partial-detail'),
    url(r'^' + prefix + 'mapmaker/partial/empty.html$', TemplateView.as_view(template_name="map_maker/partials/empty.html"), name='mapmaker-partial-empty'),
)


admin.autodiscover()
urlpatterns += patterns('',
    (r'^' + prefix + 'admin/', include(admin.site.urls)),
)


# Must serve static assets with a _real_ web server. This is not suitable for production!
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^' + prefix + 'files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'^' + prefix + 'static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
        url(r'^' + prefix + 'maps/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MAP_PUBLISH_DIR, 'show_indexes': True}, name='frontend-maps'),
        url(r'^' + prefix + 'feeds/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.FEED_OUTPUT_DIR, 'show_indexes': True}, name='feeds'),
    )

urlpatterns += patterns('',
    url(r'^' + prefix + 'maps/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MAP_PUBLISH_DIR, 'show_indexes': True}, name='frontend-maps'),
    url(r'^' + prefix + 'feeds/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.FEED_OUTPUT_DIR, 'show_indexes': True}, name='feeds'),
)

map_server/models.py
# coding=UTF-8

import logging
log = logging.getLogger(__name__)

import os
import csv
from os.path import join
from datetime import datetime, timedelta
from django.db import models
from django.conf import settings
from django.template import Context
from django.utils import simplejson
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.forms.models import model_to_dict
from django.template.loader import get_template
from post_office import mail
from map_server.utils import truncate, hashed_uid, slugify
from map_server.utils.transform import british_grid_to_wgs, irish_grid_to_wgs


class Map(models.Model):
    name = models.CharField(max_length=64, default='New Map', unique=True)
    center_latitude = models.DecimalField(decimal_places=7, max_digits=10, default=54.7)
    center_longitude = models.DecimalField(decimal_places=7, max_digits=10, default=-2.0)
    initial_zoom = models.PositiveSmallIntegerField(default=6)
    layers = models.ManyToManyField('Layer', blank=True, null=True)
    tile_set = models.CharField(max_length=32, default='google.maps.MapTypeId.TERRAIN', choices=(('google.maps.MapTypeId.TERRAIN', 'Terrain'), ('google.maps.MapTypeId.ROADMAP', 'Roadmap'),))
    specific_js = models.TextField(blank=True)
    specific_css = models.TextField(blank=True)
    specific_html = models.TextField(blank=True)
    shareable_url_root = models.CharField(max_length=512, blank=True)
    published_url = models.CharField(max_length=512, blank=True)
    accept_submissions = models.BooleanField(default=False)
    submission_header_html = models.TextField(blank=True)

    def __unicode__(self):
        return u'%s' % self.name

    def render(self):
        t = get_template('rendered_maps/template.html')
        rendered_map = t.render(Context({'map': self}))
        return rendered_map

    def preview(self):
        return HttpResponse(self.render())

    def write_to_disk(self):
        filename = '%s.html' % slugify(self.name)
        self.published_url = settings.MAP_PUBLISH_ROOT_URL + filename
        self.save()
        with open(join(settings.MAP_PUBLISH_DIR, filename), 'w+') as f:
            f.write(self.render())

    def get_submissions_layer_name(self):
        for layer in self.layers.all():
            for dataset in layer.datasets.all():
                if dataset.source_type == 'user_submissions':
                    return layer.name


class Layer(models.Model):
    name = models.CharField(max_length=64, default='New Layer')
    datasets = models.ManyToManyField('LayerDataset', blank=True, null=True)
    visible = models.BooleanField(default=False)
    marker_icons = models.ManyToManyField('MarkerIcon', blank=True, null=True)
    legend_icon = models.ForeignKey('MarkerIcon', related_name='layer_legend_icon', blank=True, null=True)
    should_cluster = models.BooleanField(default=True)
    cluster_icon = models.ForeignKey('MarkerIcon', related_name='layer_cluster_icons', blank=True, null=True)
    cluster_text_color = models.CharField(max_length=6, default='000000')  # stored in hex
    z_index = models.PositiveSmallIntegerField(default=0)

    class Meta:
        ordering = ['id']

    def __unicode__(self):
        return u'%s' % self.name


class LayerDataset(models.Model):
    name = models.CharField(max_length=64, default='New Dataset')
    source_location = models.CharField(max_length=64, blank=True)
    source_type = models.CharField(max_length=16, default='fusion', choices=(('fusion', 'Fusion Table'), ('source_code', 'Source Code'), ('json', 'JSON Feed'), ('xml', 'XML Feed'), ('user_submissions', 'User Submissions'),))
    render_location = models.CharField(max_length=16, default='local', choices=(('local', 'Local'), ('remote', 'Remote'),))
    latitude_field = models.CharField(max_length=64, default='lat')
    longitude_field = models.CharField(max_length=64, default='lng')
    decimal_precision = models.PositiveSmallIntegerField(default=3)  # Default of 3 is ~110 meters. http://gis.stackexchange.com/questions/8650/how-to-measure-the-accuracy-of-latitude-and-longitude
    field_override = models.TextField(blank=True)
    fusion_styles = models.TextField(blank=True)
    popup_html = models.TextField(blank=True)
    parser = models.TextField(blank=True)
    max_result_count = models.PositiveSmallIntegerField(blank=True, null=True)
    render_frequency_in_minutes = models.PositiveSmallIntegerField(default=30) # TODO add so cronjob runs every minute and only renders when appropriate
    last_render_time = models.DateTimeField(default=datetime.now)
    render_status = models.CharField(max_length=16, default='waiting', choices=(('waiting', 'Waiting'), ('running', 'Running'), ('failed', 'Failed'),))

    def __unicode__(self):
        if self.name:
            return u'%s' % self.name
        elif self.id:
            return u'Data Source %s' % self.id
        else:
            return u'New Data Source'

    def save(self, *args, **kwargs):
        self.popup_html = self.popup_html.replace('\n', '')
        # if self.source_type == 'user_submissions' and not self.source_location:
        #     self.source_location = reverse('approved_submissions_feed', id=map.id)
        # If source_type is a source code and the feed doesn't exist, write it out for the first time
        if self.source_type == 'source_code' and self.source_location and not os.path.exists(self.get_filename()):
            self.write_feed()
        super(LayerDataset, self).save(*args, **kwargs)

    def get_filename(self):
        return '%s.json' % slugify(self.name)

    def get_feed_url(self):
        return settings.FEED_URL + self.name + '.json'

    def write_feed(self):
        with open(join(settings.FEED_OUTPUT_DIR, self.get_filename()), 'w+') as f:
            json = self.get_source_code_feed_data()
            # Check for < 50% filesize difference (yes, just compare string lengths)
            if len(json) > len(f.read())/2:
                f.write(json)

    def generate_feed(self):
        max_hours_to_reset = 6
        if datetime.now() - self.last_render_time > timedelta(hours=max_hours_to_reset):
            # Force a reset if it's been over max_hours_to_reset hours
            log.error('Reset %s feed generation.  Has stalled for %s hours.' % (self.name, max_hours_to_reset))
            self.render_status = 'waiting'
            self.save()
        if self.render_status == 'waiting' and datetime.now() - self.last_render_time > timedelta(minutes=self.render_frequency_in_minutes):
            log.debug('Rendering %s feed.' % self.name)
            self.render_status = 'running'
            self.save()
            try:
                self.write_feed()
                self.last_render_time = datetime.now()
                self.render_status = 'waiting'
                log.info('%s rendered to %s at %s. Next render in %s minutes' %
                         (self.name, self.get_filename(), self.last_render_time, self.render_frequency_in_minutes))
            except Exception as e:
                self.render_status = 'failed'
                log.error('Render failed for dataset %s (id:%s):\n  %s' % (self.name, self.id, e))
            self.save()
        else:
            log.debug('Skipping render for %s. Last render at %s, frequency set to %s, current status of %s' %
                      (self.name, self.last_render_time, self.render_frequency_in_minutes, self.render_status))


class MarkerIcon(models.Model):
    name = models.CharField(max_length=64, blank=True)
    icon = models.FileField(upload_to='markers', null=True, blank=True)

    def __unicode__(self):
        if self.name:
            return u'%s' % self.name
        elif self.id:
            return u'Marker %s' % self.id
        else:
            return u'New Marker'


class UserSubmission(models.Model):
    map = models.ForeignKey(Map)
    photo = models.FileField(upload_to='uploaded', null=True, blank=True)  # TODO: Consider ImageField and requiring Pillow if PIL will build easily on SUSE
    postcode = models.CharField(max_length=8, blank=True)  # Should form validate one of postcode or lat/lng pair is submitted?
    # latitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    latitude = models.FloatField(blank=True, null=True)
    # longitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    firstname = models.CharField(blank=True, max_length=64)
    lastname = models.CharField(blank=True, max_length=64)
    email = models.CharField(blank=True, max_length=64)
    description = models.TextField(blank=True)
    data_protection_can_send = models.BooleanField(default=False)
    color = models.CharField(max_length=6, blank=True)  # stored in hex
    uid = models.CharField(blank=True, max_length=64)
    approval_status = models.CharField(max_length=16, default='pending',
                                       choices=(('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'),))
    approval_email_sent = models.BooleanField(default=False)
    geocoding_attempts = models.PositiveSmallIntegerField(default=0)

    class Meta:
        verbose_name = "User Submitted Photo"

    def save(self, *args, **kwargs):
        """Mail sending offloaded to post_office. Is async"""
        if self.approval_status == 'accepted' and self.email and not self.approval_email_sent:
            try:
                # TODO move address to settings
                mail.send([self.email], 'contactus@example.com', template='approved',
                          context={'name': self.firstname, 'email_address': self.email, 'uid': self.uid},)
                self.approval_email_sent = True
            except:
                log.critical('Could not send submission approval e-mail. Email template not set?')
        super(UserSubmission, self).save(*args, **kwargs)
        if not self.uid:

map_server/forms.py
from django import forms
from django.forms import ModelForm
from map_server.models import UserSubmission


class UserSubmissionForm(ModelForm):
    # latitude = forms.CharField(widget=forms.HiddenInput, required=False)
    # longitude = forms.CharField(widget=forms.HiddenInput, required=False)
    # user_name = forms.CharField(label='Your name')
    # user_email = forms.EmailField(label='E-mail Address')

    class Meta:
        model = UserSubmission
        exclude = ('approval_status',)


class ConvertEnToLatlngForm(forms.Form):
    file_to_convert = forms.FileField()


class BulkGeocodeForm(forms.Form):
    file_to_convert = forms.FileField()

map_server/templates/rendered_maps/template.html
{% load static from staticfiles %}
{% load url from future %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{{ map.name }}{% if not "map" in map.name|lower %} Map{% endif %}</title>
        <script src="{% static 'js/lib/jquery-1.9.1.min.js' %}"></script>
        <link href="{% static 'rendered_maps/map.css' %}" rel="stylesheet">
        <!--[if lte IE 8]><link href="{% static 'rendered_maps/map_ie.css' %}" rel="stylesheet"><![endif]-->

        <!-- map specific CSS -->
        {{ map.specific_css|safe }}
        <!-- / map specific CSS -->

        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-2506285-1']);
            _gaq.push(['_trackPageview']);

            (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </head>
    <body>
        <div class="foeMapping">
            <div id="map"></div>

            <div id="legend" data-toggle="max">
                <div id="minimize_button"><i class="icon icon-resize-small"></i></div>
            </div>

            <form id="postcode_locator" action="">
                <label for="postcode_input">
                    <input id="postcode_input" type="text" name="name" maxlength="8" placeholder="Postcode">
                </label>
                <input type="submit" value="Search">
                <br>
                <div id="geolocate_feature" style="display:none;">
                    <label style="display: block; text-align: center; margin: 5px 0; font-weight: bold;">OR</label>
                    <img class="geolocateicon" src="{% static 'rendered_maps/img/geolocate-icon.png' %}"><input type="button" id="geolocate_button" value="Find me on the map">
                </div>
            </form>

            <button id="share_button">Get Shareable Link</button>
            <input id="share_url" type="text">


            {% if map.accept_submissions %}
            <div id="add_your_pin_container">
                <div id="add_your_pin_button" class="bigOrange divButton"><img src="/maps/static/rendered_maps/img/markers/user.png"><p>Add your own pin</p></div>
            </div>

            <form id="add_your_pin_form" action="/maps/plain/post/" method="POST" enctype="multipart/form-data" target="iframe-post-form">
                <div id="close_button" class="divButton closeForm"><p>X</p></div>
                <div id="form_body">
                    {%  if map.submission_header_html %}
                        {{ map.submission_header_html|safe }}
                    {% else %}
                        <h2>Share your Activity</h2>
                        <p>Send us a description and photo</p>
                    {% endif %}
                    <input id="id_latitude" name="latitude" type="hidden">
                    <input id="id_longitude" name="longitude" type="hidden">
                    <input id="id_map" name="map" type="hidden" value="{{ map.id }}">

					<div class="formimage">
						<img style="" src="/maps/static/rendered_maps/img/user-pin-large.png" />
					</div>
                    <div class="textfields">
                        <input id="id_firstname" name="firstname" type="text" placeholder="First name">
                        <input id="id_lastname" name="lastname" type="text" placeholder="Surname">
                        <input id="id_email" name="email" type="text" placeholder="Email">
                        <input id="id_postcode" name="postcode" type="text" maxlength="8" placeholder="Postcode">
                    </div>

                    <textarea cols="30" id="id_description" name="description" rows="3" placeholder="Message"></textarea>

                    <label class="upload-photo-label" style="color: white;"><strong>Upload photo</strong> (optional)</label>
					<input id="id_photo" name="photo" type="file" accept="image/*" style="">

                    <button type="submit" class="bigOrange divButton bigOrange-submit">Submit</button>
                    <label class="smallprint" id="dp">
                        <input id="id_data_protection" name="data_protection_can_send" type="checkbox" checked>
                        If you prefer we do not send you information about our activities, untick this box.
                    </label>
					<p class="smallprint">Submissions are moderated. Pins display name and message/photo at the postcode provided.</p>
                </div>

                <div id="form_confirmation">
                    <h2>Thank you for your submission</h2>
                    <p>Your pin is currently awaiting approval.<br>You'll receive an email if it has been accepted.</p>
					<img style="" src="/maps/static/rendered_maps/img/user-pin-large.png" />
                    <button class="bigOrange divButton closeForm" type="button" style="text-align: center;">Close</button>
                </div>
            </form>

            <!-- Placeholder support for IE lte 9 -->
            <!--[if lte IE 9]>
                <script src="/maps/static/js/lib/jquery.placeholder.min.js" ></script>
                <script>$(function() { $('input[placeholder], textarea[placeholder]').placeholder(); });</script>
            <![endif]-->
            {% endif %}

            <!-- map specific HTML -->
            {{ map.specific_html|safe }}
            <!-- / map specific HTML -->
        </div>

        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
        <script src="{% static 'js/lib/underscore-min.js' %}"></script>
        <script src="{% static 'js/lib/markerclusterer.js' %}"></script>
        <script src="{% static 'js/lib/jquery.xml2json.js' %}"></script>
        <script src="{% static 'js/lib/handlebars.js' %}"></script>
        <script src="{% static 'js/lib/jquery.cookie.js' %}"></script>
        <script src="{% static 'js/lib/jquery.validate.1.11.1.min.js' %}"></script>
        <script src="{% static 'js/lib/jquery.iframe-post-form.js' %}"></script>
        <!--[if lte IE 8]><script src="{% static 'js/lib/es5-shim.min.js' %}"></script><![endif]-->

        <script src="{% static 'rendered_maps/foemap.js' %}"></script>

        <script type="text/javascript">
            var foeMap;

            $(function ()
            {   foeMap = new FoeMap(
                {   name: "{{ map.name }}",
                    id: {{ map.id }},
                    tile_set: {{ map.tile_set }},
                    center_lat_lng: new google.maps.LatLng({{ map.center_latitude }}, {{ map.center_longitude }}),
                    initial_zoom: {{ map.initial_zoom }},
                    {% if map.accept_submissions %}
                    accept_submissions: true,
                    submissions_layer_name: '{{ map.get_submissions_layer_name }}',
                    {% endif %}
                    shareable_url_root: '{{ map.shareable_url_root }}'
                });

                var layer;
                {% for layer in map.layers.all %}
                //////////////////// {{ layer.name|title }} Layer ////////////////////

                layer = new FoeMap.Layer(
                {   name: '{{ layer.name }}',
                    parent_map: foeMap,
                    visible: {{ layer.visible|lower }},
                    icons: [{% for icon in layer.marker_icons.all %}'/maps/files/{{ icon.icon }}'{% if not forloop.last %},{% endif %}{% endfor %}],
                    cluster: {{ layer.should_cluster|lower }},
                    {% if layer.legend_icon %}legend_icon: '/maps/files/{{ layer.legend_icon.icon }}',
                    {% endif %}{% if layer.cluster_icon %}cluster_icon: '/maps/files/{{ layer.cluster_icon.icon }}',
                    {% endif %}{% if layer.cluster_text_color %}cluster_text_color: '{{ layer.cluster_text_color }}',
                    {% endif %}{% if layer.z_index %}z_index: {{ layer.z_index }},
                    {% endif %}datasets: []
                });
                {% for dataset in layer.datasets.all %}
                layer.addDataset(new FoeMap.Dataset(
                {   name: '{{ dataset.name }}',
                    parent_layer: layer,
                    {% if dataset.source_type == 'source_code' %}source_location:'/maps/feeds/{{ dataset.name|slugify }}.json',
                    source_type: 'json',
                    {% elif dataset.source_type == 'user_submissions' %}source_location:'{% url 'approved_submissions_feed' map_id=map.id %}',
                    source_type: 'json',
                    {% elif dataset.source_type %}source_location:'{{ dataset.source_location }}',
                    source_type: '{{ dataset.source_type }}',
                    {% endif %}{% if dataset.render_location %}render_location: '{{ dataset.render_location }}',
                    {% endif %}{% if dataset.field_override %}fields: {{ dataset.field_override|safe }},
                    {% elif dataset.latitude_field and dataset.longitude_field %}fields: { lat: '{{ dataset.latitude_field }}', lng: '{{ dataset.longitude_field }}'},
                    {% endif %}{% if dataset.fusion_styles %}fusion_styles: {{ dataset.fusion_styles|safe }},
                    {% endif %}{% if dataset.max_result_count %}max_marker_count: {{ dataset.max_result_count }},
                    {% endif %}{% if dataset.popup_html %}popup_html:'{{ dataset.popup_html|safe }}',
                    {% endif %}{% if dataset.parser %}parser:{{ dataset.parser|safe }},
                    {% endif %}trailing_comma_antiemetic_for_ie: null
                }));
                {% endfor %}

                foeMap.addLayer(layer);
                {% endfor %}
                foeMap.render();


                /*   map specific JS   */
                {{ map.specific_js|safe }}
                /*  / map specific JS   */
            });
        </script>
    </body>
</html>